[tasks.rust-fmt-check]
command = "cargo"
args = ["fmt", "--check"]

[tasks.rust-fmt-fix]
command = "cargo"
args = ["fmt"]

[tasks.rust-build]
command = "cargo"
args = ["build", "--release"]

[tasks.rust-test]
command = "cargo"
args = ["test", "--verbose"]

[tasks.rust-lint-check]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.rust-lint-fix]
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--all-features",
  "--fix",
  "--",
  "-D",
  "warnings",
]

[tasks.rust-type-check]
command = "cargo"
args = ["check", "--all-features"]

[tasks.python-fmt-check]
command = "uv"
args = ["run", "ruff", "format", "--check"]

[tasks.python-fmt-fix]
command = "uv"
args = ["run", "ruff", "format"]

[tasks.python-build]
command = "uv"
args = ["run", "maturin", "build", "--release", "--features", "python"]

[tasks.python-install]
script_runner = "bash"
script = '''
  uv run python -m pip install --force-reinstall target/wheels/silk_chiffon-*.whl
'''
dependencies = ["python-build"]

[tasks.python-test]
command = "uv"
args = ["run", "pytest"]
dependencies = ["python-install"]

[tasks.python-lint-check]
command = "uv"
args = ["run", "ruff", "check"]

[tasks.python-lint-fix]
command = "uv"
args = ["run", "ruff", "check", "--fix"]

[tasks.python-type-check]
command = "uv"
args = ["run", "pyright"]

[tasks.benchmark]
command = "cargo"
args = ["bench"]

[tasks.fmt-check]
dependencies = ["python-fmt-check", "rust-fmt-check"]

[tasks.fmt-fix]
dependencies = ["python-fmt-fix", "rust-fmt-fix"]

[tasks.lint-check]
dependencies = ["python-lint-check", "rust-lint-check"]

[tasks.lint-fix]
dependencies = ["python-lint-fix", "rust-lint-fix"]

[tasks.build]
clear = true
dependencies = ["python-build", "rust-build"]

[tasks.test]
clear = true
dependencies = ["python-test", "rust-test"]
