[tasks.rust-fmt]
command = "cargo"
args = ["fmt"]

[tasks.rust-fmt-check]
command = "cargo"
args = ["fmt", "--check"]

[tasks.rust-build]
command = "cargo"
args = ["build", "--release"]

[tasks.rust-test]
command = "cargo"
args = ["test", "--verbose"]

[tasks.rust-lint]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.rust-type-check]
command = "cargo"
args = ["check", "--all-features"]

[tasks.python-fmt]
command = "uv"
args = ["run", "ruff", "format"]

[tasks.python-fmt-check]
command = "uv"
args = ["run", "ruff", "format", "--check"]

[tasks.python-build]
command = "uv"
args = ["run", "maturin", "build", "--release", "--features", "python"]

[tasks.python-install]
script_runner = "bash"
script = '''
  uv run python -m pip install --force-reinstall target/wheels/silk_chiffon-*.whl
'''
dependencies = ["python-build"]

[tasks.python-test]
command = "uv"
args = ["run", "pytest"]
dependencies = ["python-install"]

[tasks.python-lint]
command = "uv"
args = ["run", "ruff", "check"]

[tasks.python-type-check]
command = "uv"
args = ["run", "pyright"]
