[package]
name = "silk-chiffon-storage"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
description = "Object storage integration for Silk Chiffon"

[features]
default = ["local"]
local = ["object_store/fs"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
humantime.workspace = true
object_store = { workspace = true, features = ["cloud"] }
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
bytes = "^1.12.1"
futures = "^0.3.33"
tempfile = "^3.27.0"
tokio = { version = "^1.53.1", features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
