[package]
name = "silk-chiffon-test-support"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
description = "Development-only fixtures for Silk Chiffon"

[dependencies]
anyhow.workspace = true
arrow = { workspace = true, features = ["ipc_compression"] }
futures.workspace = true
parquet = { version = "^58.4.0", features = ["default", "async", "json", "arrow_canonical_extension_types"] }
silk-chiffon-storage = { path = "../silk-chiffon-storage", default-features = false, features = ["local"] }
tokio = { version = "^1.53.1", features = ["rt", "sync"] }
url.workspace = true

[dev-dependencies]
tempfile = "^3.27.0"

[lints]
workspace = true
