[package]
name = "silk-chiffon-format-arrow"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
description = "Arrow IPC format support for Silk Chiffon"

[dependencies]
anyhow.workspace = true
arrow = { workspace = true, features = ["ipc_compression"] }
async-stream = "^0.3.6"
async-trait.workspace = true
bytes = "^1.12.1"
clap.workspace = true
datafusion = { workspace = true, features = ["array_expressions", "default"] }
datafusion-datasource = "=54.1.0"
futures.workspace = true
humansize = "^2.1.3"
num-format = "^0.4.4"
object_store.workspace = true
owo-colors = "^4.3.0"
parking_lot.workspace = true
serde = { version = "^1.0.229", features = ["derive"] }
serde_json.workspace = true
silk-chiffon-core = { path = "../silk-chiffon-core" }
silk-chiffon-inspection-output = { path = "../silk-chiffon-inspection-output" }
silk-chiffon-storage = { path = "../silk-chiffon-storage", default-features = false }
tabled = { version = "^0.21.0", features = ["ansi"] }
tokio = { version = "^1.53.1", features = ["rt", "sync"] }
tokio-util.workspace = true
url.workspace = true

[dev-dependencies]
chrono = "^0.4.45"
silk-chiffon-storage = { path = "../silk-chiffon-storage", default-features = false, features = ["local"] }
silk-chiffon-test-support = { path = "../silk-chiffon-test-support" }
tempfile = "^3.27.0"

[lints]
workspace = true
