name: Python CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  python-ci:
    name: Python CI for ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup DuckDB
        uses: opt-nc/setup-duckdb-action@v1.0.13
        with:
          version: v1.3.1

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rye
        uses: eifinger/setup-rye@v3
        with:
          enable-cache: true
          cache-prefix: "rye-cache"

      - name: Install dependencies
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          rye pin $PYTHON_VERSION
          rye sync --no-lock

      - name: Build and install Python module
        run: |
          rye run maturin build --release --features python
          rye run python -m pip install --force-reinstall target/wheels/*.whl

      - name: Check Python formatting
        run: rye fmt --check

      - name: Lint Python code
        run: rye lint

      - name: Type check
        if: matrix.python-version == '3.12' && matrix.os == 'ubuntu-latest'
        run: rye run pyright

      - name: Run Python tests
        run: rye test
