name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      binary_version: ${{ steps.version.outputs.binary_version }}
      release_version: ${{ steps.version.outputs.release_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          CALVER=$(TZ=America/Chicago date '+%Y-%m-%d_%H-%M-%S')
          SHORT_SHA=$(git rev-parse --short=8 "${GITHUB_SHA}")
          BINARY_VERSION="${CALVER}_${SHORT_SHA}"

          echo "binary_version=${BINARY_VERSION}" >> "$GITHUB_OUTPUT"
          echo "release_version=v${BINARY_VERSION}" >> "$GITHUB_OUTPUT"

  build:
    needs: version
    env:
      SILK_CHIFFON_WATCH_GIT_REF: "1"
      SILK_CHIFFON_VERSION_OVERRIDE: ${{ needs.version.outputs.binary_version }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            os: linux
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-24.04-arm
            os: linux
          - target: aarch64-apple-darwin
            runner: macos-latest
            os: macos

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/sccache-action

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install system dependencies
        if: matrix.os == 'linux'
        run: sudo apt-get update && sudo apt-get install -y lld

      - name: Install packages
        if: matrix.os == 'macos'
        run: brew install lld

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-${{ matrix.runner }}"

      - name: Install cargo-zigbuild
        if: matrix.os == 'linux'
        # the python package also installs ziglang
        run: pip3 install cargo-zigbuild

      - name: Build binary
        if: matrix.os == 'macos'
        run: cargo build --locked --release --target ${{ matrix.target }}

      - name: Build binary
        if: matrix.os == 'linux'
        # links against older version of libc, makes it more compatible with older distros
        run: cargo zigbuild --locked --release --target ${{ matrix.target }}

      - name: Test binary
        run: |
          ACTUAL="$(./target/${{ matrix.target }}/release/silk-chiffon --version)"
          EXPECTED="silk-chiffon ${{ needs.version.outputs.binary_version }}"
          test "${ACTUAL}" = "${EXPECTED}"

      - name: Rename binary
        run: |
          cp \
            target/${{ matrix.target }}/release/silk-chiffon \
            target/${{ matrix.target }}/release/silk-chiffon-${{ matrix.target }}
          gzip -9 target/${{ matrix.target }}/release/silk-chiffon-${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: silk-chiffon-${{ matrix.target }}-${{ needs.version.outputs.binary_version }}
          path: target/${{ matrix.target }}/release/silk-chiffon-${{ matrix.target }}.gz
          compression-level: 0

  release:
    needs:
      - build
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./binaries

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${{ needs.version.outputs.release_version }}"
          gh release create ${VERSION} \
            --title "💝 Release ${VERSION}" \
            --generate-notes \
            ./binaries/**/*
