name: Rust Release Dev

on:
  workflow_dispatch:

env:
  DUCKDB_VERSION: 1.3.2

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag and create release
        id: tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="dev-$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

          # Create the release
          gh release create "$TAG" \
            --title "Dev Build $TAG" \
            --notes "Development build from commit ${{ github.sha }}" \
            --prerelease
  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: silk-chiffon-linux-x64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: silk-chiffon-macos-arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup DuckDB (Ubuntu amd64 only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -L -O https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-linux-amd64.zip
          unzip libduckdb-linux-amd64.zip -d libduckdb
          sudo mv libduckdb/duckdb.* /usr/local/include/
          sudo mv libduckdb/libduckdb.so /usr/local/lib/
          sudo ldconfig /usr/local/lib
          rm -rf libduckdb libduckdb-linux-amd64.zip
      - name: Setup DuckDB (Ubuntu arm64 only)
        if: ${{ matrix.os == 'ubuntu-24.04-arm' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -L -O https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-linux-arm64.zip
          unzip libduckdb-linux-arm64.zip -d libduckdb
          sudo mv libduckdb/duckdb.* /usr/local/include/
          sudo mv libduckdb/libduckdb.so /usr/local/lib/
          sudo ldconfig /usr/local/lib
          rm -rf libduckdb libduckdb-linux-arm64.zip
      - name: Setup DuckDB (macOS only)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install duckdb
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Modify the rust toolchain version
        run: rustup override set stable
      - name: Update rustup and rust
        run: rustup update
      - name: Output rust toolchain version
        run: rustup show
      - name: Output rust version for educational purposes
        run: rustup --version

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.artifact_name }}.tar.gz silk-chiffon
          echo "ASSET_PATH=${{ matrix.artifact_name }}.tar.gz" >> $GITHUB_ENV
      - name: Upload to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ needs.create-release.outputs.tag }}" "${{ env.ASSET_PATH }}" --clobber
  build-wheels:
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup DuckDB (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip build-essential
          curl -L -O https://github.com/duckdb/duckdb/releases/download/v1.3.2/libduckdb-linux-amd64.zip
          unzip libduckdb-linux-amd64.zip -d libduckdb
          sudo mv libduckdb/duckdb.* /usr/local/include/
          sudo mv libduckdb/libduckdb.so /usr/local/lib/
          sudo ldconfig /usr/local/lib
          rm -rf libduckdb libduckdb-linux-amd64.zip

      - name: Setup DuckDB (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install duckdb

      # Setup Rust
      - name: Setup Rust
        run: |
          rustup override set stable
          rustup update
          rustup show

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked

      - name: Build Python wheel (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          uv run maturin build --release --features python

      - name: Build Python wheel (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          uv run maturin build --release --features python

      - name: Upload wheels to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for wheel in target/wheels/*.whl; do
            gh release upload "${{ needs.create-release.outputs.tag }}" "$wheel" --clobber
          done
