name: Rust CI

on:
  push:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-ci:
    name: Rust CI for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo make lint

      - name: Run tests
        run: cargo test --verbose

      - name: Check
        run: cargo check --all-features
